src/Entity/News.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;

use Doctrine\ORM\Mapping as ORM;

#[ApiResource(
    operations: [
        new Get(),
        new GetCollection()
    ],
)]
#[ORM\Entity(repositoryClass: "App\Repository\NewsRepository")]
class News
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private $id;

    #[ORM\Column(type: "string", length: 100)]
    private $title;

    #[ORM\Column(type: "text")]
    private $content;

    #[ORM\Column(type: "string", length: 255)]

    private $summary;

    #[ORM\ManyToOne(targetEntity: "App\Entity\Project", inversedBy: "news")]
    private $project;

    #[ORM\Column(type: "string", length: 255)]
    private $reference;

    #[ORM\Column(type: "datetimetz")]
    private $created_on;

    #[ORM\Column(type: "datetimetz", nullable: true)]
    private $updated_on;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): self
    {
        $this->project = $project;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getCreatedOn(): ?\DateTimeInterface
    {
        return $this->created_on;
    }

    public function setCreatedOn(\DateTimeInterface $created_on): self
    {
        $this->created_on = $created_on;

        return $this;
    }

    public function getUpdatedOn(): ?\DateTimeInterface
    {
        return $this->updated_on;
    }

    public function setUpdatedOn(?\DateTimeInterface $updated_on): self
    {
        $this->updated_on = $updated_on;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Doctrine\Common\Collections\Criteria;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use App\Repository\NewsRepository;

class MainController extends AbstractController
{
    #[Route("/", methods: ["GET"])]
    public function home(
        NewsRepository $newsDb
    ) {
        $itemPerPage = 9;

        $criteria = Criteria::create()
            ->setMaxResults($itemPerPage);

        $news = $newsDb
            ->findAllOrderedByCreatedOn($criteria);

        return $this->render('main/home.html.twig', [
            'itemsPerPage' => $itemPerPage,
            'news' => $news,
        ]);
    }
}

templates/main/home.html.twig
{# templates/main/home.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
<div class="mb-4 px-4 py-5 text-black bg-light">
	<h1 class="display-4">Trogon {% include "logo.html.twig" %}</h1>
	<p class="lead">Welcome to Trogon official webpage. Here you can fild information about ongoing projects.</p>
</div>

<div id="news" data-items-per-page="{{ itemsPerPage }}">
	<div class="row">
{% for item in news %}
		<div class="col-md-4">
			<div class="card mb-4 shadow-sm">
				<div class="card-header">
					{{ item.title }}
				</div>
				<div class="card-body">
					<p class="card-text">{{ item.summary | raw }}</p>
					<div class="d-flex justify-content-between align-items-center">
						{# <div class="btn-group">
							<button class="btn btn-sm btn-outline-secondary" type="button">Read more »</button>
						</div> #}
						<small class="text-muted">{{ item.createdOn | date }}</small>
					</div>
				</div>
			</div>
		</div>
{% endfor %}
	</div>
</div>

{% endblock %}

{% block stylesheets %}
{{ parent() }}
		{{ encore_entry_link_tags('news') }}
{% endblock %}

{% block javascripts %}
{{ parent() }}
		{{ encore_entry_script_tags('news') }}
{% endblock %}