src/Entity/Project.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ApiResource(
    operations: [
        new Get(),
        new GetCollection()
    ],
)]
#[ORM\Entity(repositoryClass: "App\Repository\ProjectRepository")]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private $id;

    #[ORM\Column(type: "string", length: 255)]
    private $provider;

    #[ORM\Column(type: "string", length: 255)]
    private $name;

    #[ORM\Column(type: "string", length: 255)]
    private $full_name;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private $license;

    #[ORM\Column(type: "string", length: 255)]
    private $description;

    #[ORM\Column(type: "string", length: 255)]
    private $repo_link;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private $website;

    #[ORM\Column(type: "string", length: 20, nullable: true)]
    private $language;

    #[ORM\Column(type: "boolean")]
    private $is_private;

    #[ORM\Column(type: "boolean")]
    private $is_archived;

    #[ORM\Column(type: "datetimetz")]
    private $created_on;

    #[ORM\Column(type: "datetimetz")]
    private $updated_on;

    #[ORM\OneToMany(targetEntity: "App\Entity\News", mappedBy: "project")]
    private $news;

    public function __construct()
    {
        $this->news = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProvider(): ?string
    {
        return $this->provider;
    }

    public function setProvider(string $provider): self
    {
        $this->provider = $provider;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->full_name;
    }

    public function setFullName(string $full_name): self
    {
        $this->full_name = $full_name;

        return $this;
    }

    public function getLicense(): ?string
    {
        return $this->license;
    }

    public function setLicense(?string $license): self
    {
        $this->license = $license;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getRepoLink(): ?string
    {
        return $this->repo_link;
    }

    public function setRepoLink(string $repo_link): self
    {
        $this->repo_link = $repo_link;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(?string $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function getIsPrivate(): ?bool
    {
        return $this->is_private;
    }

    public function setIsPrivate(bool $is_private): self
    {
        $this->is_private = $is_private;

        return $this;
    }

    public function getIsArchived(): ?bool
    {
        return $this->is_archived;
    }

    public function setIsArchived(bool $is_archived): self
    {
        $this->is_archived = $is_archived;

        return $this;
    }

    public function getCreatedOn(): ?\DateTimeInterface
    {
        return $this->created_on;
    }

    public function setCreatedOn(\DateTimeInterface $created_on): self
    {
        $this->created_on = $created_on;

        return $this;
    }

    public function getUpdatedOn(): ?\DateTimeInterface
    {
        return $this->updated_on;
    }

    public function setUpdatedOn(\DateTimeInterface $updated_on): self
    {
        $this->updated_on = $updated_on;

        return $this;
    }

    /**
     * @return Collection|News[]
     */
    public function getNews(): Collection
    {
        return $this->news;
    }

    public function addNews(News $news): self
    {
        if (!$this->news->contains($news)) {
            $this->news[] = $news;
            $news->setProject($this);
        }

        return $this;
    }

    public function removeNews(News $news): self
    {
        if ($this->news->contains($news)) {
            $this->news->removeElement($news);
            // set the owning side to null (unless already changed)
            if ($news->getProject() === $this) {
                $news->setProject(null);
            }
        }

        return $this;
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use App\Service\LayoutService;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Component\HttpClient\Exception\ClientException;
use Symfony\Component\HttpClient\Exception\TransportException;

use App\Repository\ProjectRepository;

class ProjectController extends AbstractController
{
    private $showPrivate = false;

    #[Route("/projects", methods: ["GET"])]
    public function list(
        LayoutService $layout,
        ProjectRepository $projectDb
    ) {
        $layout->breadcrumbs[] = [
            'label' => 'Projects',
            'route' => 'app_project_list'
        ];

        $projects = $projectDb
            ->findBy(['is_private' => $this->showPrivate]);

        usort($projects, function ($a, $b) {
            return strcasecmp($a->getName(), $b->getName());
        });

        return $this->render('project/list.html.twig', [
            'projects' => $projects,
        ]);
    }

    #[Route("/project/{name}", methods: ["GET"])]
    public function show(
        string $name,
        LayoutService $layout,
        ProjectRepository $projectDb
    ) {
        // Replace the % decoded symbol to / separator. The name variable is already URL decoded.
        $full_name = str_replace('%', '/', $name);

        $projects = $projectDb
            ->findBy(['is_private' => $this->showPrivate, 'full_name' => $full_name]);

        usort($projects, function ($a, $b) {
            return strcasecmp($a->getName(), $b->getName());
        });

        if (count($projects) > 0) {
            $project = $projects[0];

            $layout->breadcrumbs[] = [
                'label' => 'Projects',
                'route' => 'app_project_list'
            ];
            $layout->breadcrumbs[] = [
                'label' => $project->getName(),
                'route' => 'app_project_show'
            ];

            return $this->render('project/show.html.twig', [
                'project' => $project,
            ]);
        } else {
            throw $this->createNotFoundException('The project does not exist');
        }
    }
}

templates/project/list.html.twig
{# templates/project/list.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
<div class="mb-4 px-4 py-5 text-black bg-light">
	<h1 class="display-4">Project</h1>
	<p class="lead">List of currently ongoing projects. <span id="show_hide_archived_container" class="d-none d-sm-inline float-right"></span></p>
	<hr class="my-4">
	<!-- project items block -->
	<div class="card">
		{% for item in projects %}
		<div class="card-body project{% if item.isArchived %} archived{% endif %}" data-id="{{ item.id }}">
			<h5 class="card-title">{{ item.name }} {% if item.isArchived %}<span class="badge bg-info text-dark">Archived</span>{% endif %}</h5>
			<p class="card-text">{{ item.description }}</p>
			<a href="{{ url('app_project_show', {'name': item.fullName|url_encode|replace({'%2F': '%'}) }) }}" class="btn btn-primary">Project page</a>
		</div>
			{% if not loop.last %}
		<hr{% if item.isArchived %} class="project archived"{% endif %}>
			{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock %}

{% block stylesheets %}
{{ parent() }}
		{{ encore_entry_link_tags('project') }}
{% endblock %}

{% block javascripts %}
{{ parent() }}
		{{ encore_entry_script_tags('project') }}
{% endblock %}

templates/project/show.html.twig
{# templates/project/show.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
<div class="mb-4 px-4 py-5 text-black bg-light">
	<h1 class="display-4">Project {{ project.name }}</h1>
	<p class="lead">
{% if project.provider == 'bitbucket' %}
		<img alt="Bitbucket pull requests" 
			src="{{ badge(project.provider, 'pr', project.fullName, {style:'for-the-badge'}) }}"/>
{% endif %}
{% if project.provider == 'github' %}
		<img alt="GitHub pull requests" 
			src="{{ badge(project.provider, 'issues-pr', project.fullName, {style:'for-the-badge'}) }}"/>
		<img alt="GitHub license" 
			src="{{ badge(project.provider, 'license', project.fullName, {style:'for-the-badge'}) }}"/>
		<img alt="GitHub latest version"
			src="{{ badge(project.provider, 'v/tag', project.fullName, {style:'for-the-badge', label:'Release'}) }}"/>
		<img alt="GitHub downloads"
			src="{{ badge(project.provider, 'downloads', project.fullName, {style:'for-the-badge'}, 'total') }}"/>
{% endif %}
	</p>
	<hr class="my-4">
	<!-- description block -->
	<div class="card">
		<div class="card-body">
			<h5 class="card-title">Description {% if project.isArchived %}<span class="badge bg-info text-dark">Project is archived</span>{% endif %}</h5>
			<p class="card-text">{{ project.description }}</p>
			<a href="{{ project.repoLink }}" class="btn btn-secondary">Repository page</a>
		</div>
	</div>
</div>
{% endblock %}